export const adminMembers = [
  {
    id: "maya-chen",
    name: "Maya Chen",
    email: "maya@example.com",
    plan: "The Den",
    joined: "Jul 18, 2026",
    status: "Active",
    lastActive: "Today",
    initials: "MC",
  },
  {
    id: "elena-brooks",
    name: "Elena Brooks",
    email: "elena@example.com",
    plan: "LIFT Guide",
    joined: "Jul 12, 2026",
    status: "Active",
    lastActive: "Yesterday",
    initials: "EB",
  },
  {
    id: "nora-james",
    name: "Nora James",
    email: "nora@example.com",
    plan: "The Den",
    joined: "Jun 28, 2026",
    status: "Active",
    lastActive: "2 days ago",
    initials: "NJ",
  },
  {
    id: "talia-reed",
    name: "Talia Reed",
    email: "talia@example.com",
    plan: "LIFT PDF",
    joined: "Jun 20, 2026",
    status: "Active",
    lastActive: "6 days ago",
    initials: "TR",
  },
  {
    id: "june-martin",
    name: "June Martin",
    email: "june@example.com",
    plan: "The Den",
    joined: "May 31, 2026",
    status: "Past due",
    lastActive: "12 days ago",
    initials: "JM",
  },
] as const

export const adminBookings = [
  {
    id: "booking-beauty-ritual",
    date: "Today",
    time: "10:00 AM",
    client: "Maya Chen",
    service: "HWL Beauty & Being Ritual",
    duration: "90 min",
    format: "In person",
    status: "Confirmed",
    value: "$333",
    tone: "beauty",
  },
  {
    id: "booking-sound-bath",
    date: "Today",
    time: "1:30 PM",
    client: "Private group · 4 guests",
    service: "Private Sound Bath",
    duration: "60 min",
    format: "In person",
    status: "Confirmed",
    value: "$444",
    tone: "movement",
  },
  {
    id: "booking-coaching",
    date: "Today",
    time: "4:00 PM",
    client: "Nora James",
    service: "Life Coaching",
    duration: "60 min",
    format: "Virtual",
    status: "Intake ready",
    value: "Consultation",
    tone: "ritual",
  },
  {
    id: "booking-consult",
    date: "Tomorrow",
    time: "11:30 AM",
    client: "Elena Brooks",
    service: "Private Consultation",
    duration: "45 min",
    format: "Virtual",
    status: "Pending",
    value: "Inquiry",
    tone: "ritual",
  },
  {
    id: "booking-yoga",
    date: "Aug 4",
    time: "9:00 AM",
    client: "Retreat group · 8 guests",
    service: "Private Yoga",
    duration: "75 min",
    format: "Off-site",
    status: "Confirmed",
    value: "$555",
    tone: "movement",
  },
] as const

export const adminTransactions = [
  {
    id: "txn-001",
    date: "Jul 29",
    customer: "Maya Chen",
    product: "The Den",
    amount: "$11.11",
    status: "Paid",
  },
  {
    id: "txn-002",
    date: "Jul 28",
    customer: "Elena Brooks",
    product: "LIFT Video + PDF",
    amount: "$5.55",
    status: "Paid",
  },
  {
    id: "txn-003",
    date: "Jul 27",
    customer: "Talia Reed",
    product: "LIFT PDF",
    amount: "$3.33",
    status: "Paid",
  },
  {
    id: "txn-004",
    date: "Jul 24",
    customer: "Nora James",
    product: "The Den",
    amount: "$11.11",
    status: "Paid",
  },
] as const

export const adminCourses = [
  {
    id: "lift-daily-facial-ritual",
    title: "LIFT — A Daily Facial Ritual",
    category: "Beauty",
    access: "LIFT + The Den",
    lessons: 7,
    status: "Media pending",
    description:
      "Seven intentional movements for circulation, release, sculpting, and glow.",
  },
  {
    id: "rest-and-reset",
    title: "Rest & Reset",
    category: "Movement",
    access: "The Den",
    lessons: 4,
    status: "Draft",
    description:
      "A quiet sequence of breath, sound, and restorative movement for softer evenings.",
  },
  {
    id: "seasonal-rituals",
    title: "Seasonal Rituals",
    category: "Ritual",
    access: "The Den",
    lessons: 3,
    status: "Outline",
    description:
      "Simple practices for marking transitions and returning to what matters.",
  },
] as const

export const liftLessons = [
  {
    id: "prep-the-skin",
    title: "Prep the Skin",
    duration: "1:30",
    media: "Awaiting Mux playback ID",
    status: "Draft",
  },
  {
    id: "jawline-lift",
    title: "Jawline Lift",
    duration: "2:00",
    media: "Awaiting Mux playback ID",
    status: "Draft",
  },
  {
    id: "mid-face-sculpt",
    title: "Mid-Face Sculpt",
    duration: "2:00",
    media: "Awaiting Mux playback ID",
    status: "Draft",
  },
  {
    id: "brow-lift",
    title: "Brow Lift",
    duration: "1:30",
    media: "Awaiting Mux playback ID",
    status: "Draft",
  },
  {
    id: "forehead-release",
    title: "Forehead Release",
    duration: "1:30",
    media: "Awaiting Mux playback ID",
    status: "Draft",
  },
  {
    id: "lymphatic-sweep",
    title: "Lymphatic Sweep",
    duration: "2:00",
    media: "Awaiting Mux playback ID",
    status: "Draft",
  },
  {
    id: "neck-drainage",
    title: "Neck Drainage",
    duration: "2:00",
    media: "Awaiting Mux playback ID",
    status: "Draft",
  },
] as const

export const adminArticles = [
  {
    id: "nervous-system-skin",
    title: "Why your skin changes when your nervous system is tired",
    category: "Beauty",
    status: "Draft",
    date: "Not scheduled",
    views: "—",
  },
  {
    id: "movement-as-return",
    title: "Movement as a return, not a punishment",
    category: "Movement",
    status: "Draft",
    date: "Not scheduled",
    views: "—",
  },
  {
    id: "mark-a-threshold",
    title: "How to mark a threshold",
    category: "Ritual",
    status: "Outline",
    date: "Not scheduled",
    views: "—",
  },
  {
    id: "unforgettable-retreat",
    title: "What makes a retreat unforgettable",
    category: "Retreat Living",
    status: "Outline",
    date: "Not scheduled",
    views: "—",
  },
] as const

export const adminProducts = [
  {
    id: "lift-pdf",
    name: "LIFT PDF",
    price: "$3.33",
    cadence: "One-time",
    access: "Protected PDF download",
    status: "Awaiting Stripe price",
    sales: "—",
  },
  {
    id: "lift-guide",
    name: "LIFT Video + PDF",
    price: "$5.55",
    cadence: "One-time",
    access: "Browser video + protected PDF",
    status: "Awaiting media",
    sales: "—",
  },
  {
    id: "the-den",
    name: "The Den",
    price: "$11.11",
    cadence: "Monthly",
    access: "Member library subscription",
    status: "Awaiting Stripe price",
    sales: "—",
  },
] as const

export const adminConversations = [
  {
    id: "maya-chen",
    name: "Maya Chen",
    preview: "Thank you — I felt so grounded after our session.",
    time: "10:42 AM",
    unread: true,
    plan: "The Den",
  },
  {
    id: "elena-brooks",
    name: "Elena Brooks",
    preview: "Is there a lighter pressure option for step four?",
    time: "Yesterday",
    unread: true,
    plan: "LIFT Guide",
  },
  {
    id: "nora-james",
    name: "Nora James",
    preview: "I completed the intake form for Friday.",
    time: "Monday",
    unread: false,
    plan: "The Den",
  },
] as const

export const adminJourneys = [
  {
    id: "summer-skin-reset",
    title: "Summer Skin Reset",
    type: "Sequence",
    status: "Active",
    started: "Jul 15, 2026",
    progress: "3 of 7 messages",
    enrolled: 47,
    replies: 23,
    bookings: 8,
    attributed: "$1,264",
  },
  {
    id: "moon-ritual-series",
    title: "Moon Ritual Series",
    type: "Education",
    status: "Scheduled",
    started: "Aug 15, 2026",
    progress: "0 of 4 messages",
    enrolled: 31,
    replies: 0,
    bookings: 0,
    attributed: "$0",
  },
  {
    id: "fall-retreat-prep",
    title: "Fall Retreat Prep",
    type: "Sequence",
    status: "Draft",
    started: "Sep 1, 2026",
    progress: "0 of 5 messages",
    enrolled: 0,
    replies: 0,
    bookings: 0,
    attributed: "$0",
  },
] as const

export const journeySequence = [
  {
    day: "Day 1",
    delay: "0 hours",
    subject: "Your skin is ready for a reset",
    body: "Welcome in. Here’s what to expect this week, and one simple way to begin today.",
    cta: "Watch the introduction",
    status: "Sent",
  },
  {
    day: "Day 3",
    delay: "48 hours",
    subject: "How’s the massage feeling?",
    body: "Did the lymphatic sweep feel supportive? Reply and tell me what you noticed—I read every message.",
    cta: "Book a 15-minute consult",
    status: "Sent",
  },
  {
    day: "Day 7",
    delay: "144 hours",
    subject: "You’ve done the work—time for the ritual",
    body: "If you want to go deeper, I’d love to guide you through the complete Beauty & Being Ritual.",
    cta: "Book the 90-minute ritual",
    status: "Scheduled",
  },
] as const

export const journeyConversations = [
  {
    id: "maya-summer-reset",
    journey: "Summer Skin Reset",
    member: "Maya Chen",
    email: "maya@example.com",
    plan: "The Den",
    joined: "Jul 18, 2026",
    preview: "The lymphatic sweep felt amazing—can I do it twice?",
    time: "10:42 AM",
    unread: 2,
  },
  {
    id: "elena-summer-reset",
    journey: "Summer Skin Reset",
    member: "Elena Brooks",
    email: "elena@example.com",
    plan: "LIFT Guide",
    joined: "Jul 12, 2026",
    preview: "I’m not sure how much pressure to use around my jaw.",
    time: "Yesterday",
    unread: 1,
  },
  {
    id: "nora-moon-ritual",
    journey: "Moon Ritual Series",
    member: "Nora James",
    email: "nora@example.com",
    plan: "The Den",
    joined: "Jun 28, 2026",
    preview: "I’d love to opt into the August series.",
    time: "Monday",
    unread: 0,
  },
] as const

export const journeyTemplates = [
  {
    title: "Welcome Sequence",
    description: "A warm first seven days after someone joins.",
    timing: "Day 1 · Day 3 · Day 7",
    messages: 3,
    cta: "Begin a practice",
  },
  {
    title: "Product Education",
    description: "Teach the ritual slowly, with room for questions.",
    timing: "Day 1 · Day 4 · Day 8",
    messages: 3,
    cta: "Open LIFT",
  },
  {
    title: "Booking Nudge",
    description: "A gentle invitation shaped by member interest.",
    timing: "Day 1 · Day 5",
    messages: 2,
    cta: "Book a session",
  },
  {
    title: "Seasonal Reset",
    description: "A quarterly beauty, body, and being refresh.",
    timing: "Weekly · 4 weeks",
    messages: 4,
    cta: "Choose a ritual",
  },
  {
    title: "Event Promotion",
    description: "Introduce a retreat or workshop without pressure.",
    timing: "Day 1 · Day 7 · Day 14",
    messages: 3,
    cta: "Explore the event",
  },
  {
    title: "Check-In",
    description: "Make space for a mid-cycle reply and reflection.",
    timing: "Day 14",
    messages: 1,
    cta: "Reply to Shannon",
  },
  {
    title: "Win-Back",
    description: "Reconnect with inactive members with genuine care.",
    timing: "Day 1 · Day 10",
    messages: 2,
    cta: "Return to The Den",
  },
] as const
